name: CI

on:
  push:
    branches: [ "*" ]

env:
  AZURE_WEBAPP_NAME: sqlishard
  DOTNET_VERSION: '9.0.x'

jobs:
  ci-stage:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        working-directory: ./src/backend
        run: dotnet restore

      - name: Build
        working-directory: ./src/backend
        run: dotnet build --no-restore

      - name: Test
        working-directory: ./src/backend
        run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName!~SQLisHard.IntegrationTests" --logger "trx;LogFileName=test-results.trx"
        
      # - name: Publish Test Results
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: Test Results
      #     path: "**/test-results.trx"

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: 'Test Results'
          path: '**/test-results.trx'
          reporter: dotnet-trx

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: [ci-stage]
    if: contains('refs/head/master', 'refs/head/main')
    env:
      VERSION_NUMBER: 1.0.${{ github.run_number }}-${{ github.run_attempt }}
      AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
      AZURE_SQL_SERVER_NAME: ${{ secrets.AZURE_SQL_SERVER_NAME }}
      AZURE_SQL_RESOURCE_GROUP: ${{ secrets.AZURE_SQL_RESOURCE_GROUP }}
      AZURE_SQL_DB_NAME_CORE: ${{ vars.AZURE_SQL_DB_NAME_CORE }}
      AZURE_SQL_DB_NAME_EXERCISES: ${{ vars.AZURE_SQL_DB_NAME_EXERCISES }}
      AZURE_SQL_DB_USER: ${{ secrets.AZURE_SQL_DB_USER }}
      AZURE_SQL_DB_PASSWORD: ${{ secrets.AZURE_SQL_DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        working-directory: ./src/backend
        run: dotnet restore

      - name: Build for Release
        working-directory: ./src/backend
        run: |
          echo "Version is ${{ env.VERSION_NUMBER }}"
          sed -i 's/VERSION_NUMBER/${{ env.VERSION_NUMBER }}/' ./SQLisHard/appsettings.Production.json
          dotnet publish ./SQLisHard/SQLisHard.csproj -c Release --property:PublishDir='../../../app-web' --runtime win-x86 --no-self-contained /p:EnvironmentName=Production /property:Version=${{ env.VERSION_NUMBER }}
          dotnet publish ./SQLisHard.DBMigrations/SQLisHard.DBMigrations.csproj -c Release --property:PublishDir='../../../app-migration' --no-self-contained -r linux-x64
        
      # SKIPPED: This is where our slot deploy to staging would go if we had blue/green deploys (higher cost webapp)
      # :(

      - name: Database Migration
        run: |
          ip=$(curl -s https://api.ipify.org)
          echo "Adding firewall rule for: $ip"
          az sql server firewall-rule create --subscription $AZURE_SUBSCRIPTION -s $AZURE_SQL_SERVER_NAME -g $AZURE_SQL_RESOURCE_GROUP -n GithubAction-${{ github.run_number }}-${{ github.run_attempt }} --start-ip-address $ip --end-ip-address $ip
          echo "Running migrations..."
          echo "Migration 1: Core Database (db=$AZURE_SQL_DB_NAME_CORE)"
          ./app-migration/SQLisHard.DBMigrations -m ./database/coredb/migrations --connectionString "Server=$AZURE_SQL_SERVER_NAME.database.windows.net;Database=$AZURE_SQL_DB_NAME_CORE;User ID=$AZURE_SQL_DB_USER;Password=$AZURE_SQL_DB_PASSWORD;Trusted_Connection=False;Encrypt=True"
          echo "Migration 2: Exercises Database (db=$AZURE_SQL_DB_NAME_EXERCISES)"
          ./app-migration/SQLisHard.DBMigrations -m ./database/exercisedb/migrations --connectionString "Server=$AZURE_SQL_SERVER_NAME.database.windows.net;Database=$AZURE_SQL_DB_NAME_EXERCISES;User ID=$AZURE_SQL_DB_USER;Password=$AZURE_SQL_DB_PASSWORD;Trusted_Connection=False;Encrypt=True"
          echo "Migrations Complete."

      - name: Database Firewall Cleanup
        if: always()
        run: |
          ip=$(curl -s https://api.ipify.org)
          echo "Removing firewall rule for: $ip"
          az sql server firewall-rule delete --subscription $AZURE_SUBSCRIPTION -s $AZURE_SQL_SERVER_NAME -g $AZURE_SQL_RESOURCE_GROUP -n GithubAction-${{ github.run_number }}-${{ github.run_attempt }}

      # actual deploy, this would be a slot swap if we had blue/green
      #   we'll accept the micro outages during deploy as the trade-off
      - name: Deploy Azure Webapp
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: './app-web'
      
      - name: Azure Logout
        run: |
          az logout
